### ISSUE TITLE
Can not finish install

### ISSUE THREAD

**Issue by listlesslife** [hassio-addons/addon-lutron-cert#13]
# Problem/Motivation

Setup does not prompt user for login credentials

## Expected behavior

-Click "OPEN WEB UI"
-pop up with "Click here to login to Lutron" for login credentials
-prompt for login
-provide credentials 
-receive error
-copy URL  
-edit config
-reset & done

## Actual behavior

-Click "OPEN WEB UI"
-pop up with "Click here to login to Lutron" for login credentials

-receive error
-copy URL  
-edit config
-Notification "Invalid config
The following integrations and platforms could not be set up:
lutron_caseta
Please check your config."
-reset, still disabled

## Steps to reproduce

attempt install

## Proposed changes

Bring back login. I've done this integration before, I'm just doing a fresh install of HA.

**Comment by Namak1719** [comment]
I think I am having the same bug but would be happy to help. I have never submitted logs or anything before so if you walk me through anything that is needed, I would be happy to provide it. 

Steps to reproduce:
1. Supervisor -> Lutron Certificate -> Install
2. Hit Start
3. Hit Open Web UI
--> error message: This site can't be reached. ***.duckdns.org took too long to respond.

Log from  Lutron Certificate:
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 00-banner.sh: executing... 
-----------------------------------------------------------
 Add-on: Lutron Certificate
 Generate certificate to control Lutron Caseta bridge locally
-----------------------------------------------------------
 Add-on version: 0.5.1
 You are running the latest version of this add-on.
 System: HassOS 3.13  (amd64 / qemux86-64)
 Home Assistant Core: 0.110.2
 Home Assistant Supervisor: 224
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
[cont-init.d] 00-banner.sh: exited 0.
[cont-init.d] 01-log-level.sh: executing... 
[cont-init.d] 01-log-level.sh: exited 0.
[cont-init.d] uuidgen.sh: executing... 
[cont-init.d] uuidgen.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[21:56:36] INFO: Starting Lutron certificate server...
 * Serving Flask app "cert_server" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
 * Running on http://0.0.0.0:5817/ (Press CTRL+C to quit)

**Comment by Namak1719** [comment]
Nevermind, it works now! Perhaps it is because of my DNS being too new? To get it to work, I accessed HASS through the homeassistant.local:8123 and that worked (the app opened homeassistant.local:5817 instead of ***.duckdns.org:5817).
