### ISSUE TITLE
Error 500 when two homes on one account

### ISSUE THREAD

**Issue by jeffdeal** [hassio-addons/addon-lutron-cert#16]
# Problem/Motivation

I have two homes and two Lutron hubs on the same network.  The script works great but only on one of the hubs.  When I specify the IP of the second hub I get error 500 "Internal server error" and do not get back the three certificate files.

## Expected behavior

Start the script
Sign in using the Lutron account
Grab the "error" URL
Enter the IP of the first hub
Generate certificates
Stash certificates somewhere for safekeeping
Start over
Sign in using Lutron account (same account for 2nd home)
Grab the "Error" URL
Enter IP of the second hub
Generate certificates
Stash certificates somewhere for safekeeping
Move certificates and modify configuration.yaml as necessary

## Actual behavior

Start the script
Sign in using the Lutron account
Grab the "error" URL
Enter the IP of the first hub
Generate certificates
Stash certificates somewhere for safekeeping
Start over
Sign in using Lutron account (same account for 2nd home)
Grab the "Error" URL
Enter IP of the second hub
ERROR CODE 500 - Internal Server Error

2 certificate files are generated, but not the caseta-bridge.crt

## Steps to reproduce

> (How can someone else make/see it happen)

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

I was able to get this working by using a separate Lutron account for each hub and installing the certificates.  This is not an optimal solution as it gives up easy switching between homes in the Lutron app.   I tried grabbing the certificates from each hub using the same Lutron account but the removing and adding the account to the hub seems to change the certificate, so this doesn't work.

**Comment by frenck** [comment]
Unfortunately, there is not much to do about this.
Make sure you sign out on the Lutron account, re-install the add-on and try again.
