### ISSUE TITLE
Lutron devices quit showing in HA

### ISSUE THREAD

**Issue by kandbcontrols** [hassio-addons/addon-lutron-cert#18]
#Lutron Caseta devices no longer available in HA

> (Why the issue was filed)They have bee working flawlessly for a couple of years

## Expected behavior

> (What you expected to happen)

## Actual behavior

> (What actually happened) Updated to the latest version of HA 117.6

## Steps to reproduce

> (How can someone else make/see it happen)

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

**Comment by frenck** [comment]
That sounds like an integration issue, not an add-on issue.
The add-on is a one-time deal to extract the certificates, it in no way provides an integration.
