### ISSUE TITLE
Lutron folder created under SSL folder but folder empty - Failed to import Caséta bridge configuration

### ISSUE THREAD

**Issue by ballakers** [hassio-addons/addon-lutron-cert#21]
# Problem/Motivation

> certificate add-on seems to work fine - logs are happy I believe but no certificates are being made. using Version
2020.12.7 on Rpi4 and latest lutron cert
Logs - 20-12-29 19:36:39 WARNING (MainThread) [supervisor.addons.validate] Unknown options lutron_caseta
20-12-29 19:36:42 INFO (SyncWorker_1) [supervisor.docker.interface] Stopping addon_a0d7b954_lutron-cert application
20-12-29 19:36:47 INFO (SyncWorker_1) [supervisor.docker.interface] Cleaning addon_a0d7b954_lutron-cert application
20-12-29 19:36:47 WARNING (MainThread) [supervisor.addons.validate] Unknown options lutron_caseta
20-12-29 19:36:48 INFO (SyncWorker_0) [supervisor.docker.addon] Starting Docker add-on hassioaddons/lutron-cert-armv7 with version 0.6.0
20-12-29 19:36:49 INFO (MainThread) [supervisor.api.security] /host/info access from a0d7b954_lutron-cert
20-12-29 19:37:15 INFO (SyncWorker_5) [supervisor.docker.interface] Restarting homeassistant/raspberrypi4-homeassistant

## Expected behavior

> put the certs into yaml and it will connect bridge locally - cannot do this with my missing cert info

## Actual behavior

> click web UI link within the lutron cert add-on - link cannot open and it displays the URL of my home assistant DNS setup with port :5817 at the end eg "http://blakeandevon.duckdns.org:5817/" - when i tried the first time the other day it would prompt from lutron login and then an error message came up and looked like a token or code was at the end of the error URL (when it did actually take me to a proper link) cannot reproduce what happened on my initial attempt to add the integration.
## Steps to reproduce

> Can provide screen shots
logs from Home Assistant above

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

**Comment by frenck** [comment]
> click web UI link within the lutron cert add-on - link cannot open and it displays the URL of my home assistant DNS setup with port :5817 at the end eg "http://blakeandevon.duckdns.org:5817" - when i tried the first time the other day it would prompt from lutron login and then an error message came up and looked like a token or code was at the end of the error

Open the URL locally, e.g., `http://IP_ADDRESS_ON_THE_NETWORK:5817` or `http://homeassistant.local:5817`. You are trying to reach it externally via DuckDNS, which I think sounds not the thing you want.

**Comment by ballakers** [comment]
got through to the login screen using the IP of Home Assistant and port 5817 like you said.  I then get redirected to the page with message "The page you were looking for doesn't exist" (which is what is supposed to happen right?)  Really appreciate the help - but still not quite there yet. The lutron folder is still being created (even after i delete it- so seems like add-on is doing something) in the SSL folder on the shared drive via Samba.  But the folder remains empty and no sign of cert - maybe i have to access HA via terminal to find these?  I am pretty new to this but didn't have issues with getting any of my other devices into HA other than still need to figure out ringmqttto get my alarm sensors in.  No issues with HOOBS either just can't seem to wrap my head around adding this integration to HA.  If you get me up and running I'll be forever indebted haha

**Comment by ballakers** [comment]
Hi Frenck and everyone else here are my logs below - from my little knowledge it looks like the file path isn't set up correctly. Any tips would be greatly appreciated since don't want to have to use Smartthings for my caseta lights when I can use the Lutron integration locally. 

Perhaps it is because I am using my duckDNS page at https for both internal and external url in my config.yaml for my home assistant instance.  I probably misunderstood but once you set up duckdns for HA isn't the only way to access it via the external url.  But for the lutron certificate i guess we aren't dealing with port 8123 anymore so.... not sure if I am making sense but would love and appreciate any help. 

Logs: 
2020-12-30 08:44:45 WARNING (MainThread) [homeassistant.loader] You are using a custom integration for hacs which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant.
2020-12-30 08:44:48 ERROR (MainThread) [homeassistant.components.lutron_caseta.config_flow] Unknown exception while checking connectivity to bridge 192.168.x.xx
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/components/lutron_caseta/config_flow.py", line 84, in async_validate_connectable_bridge_config
bridge = Smartbridge.create_tls(
File "/usr/local/lib/python3.8/site-packages/pylutron_caseta/smartbridge.py", line 106, in create_tls
ssl_context.load_verify_locations(ca_certs)
FileNotFoundError: [Errno 2] No such file or directory

**Comment by ballakers** [comment]
cannot solve my lutron certificate issue - when I manually go to URL of my home assistant instance IP with port 5817  eg "http://192.168.5.xx:5817/ the lutron login is prompted and i can login in and then receive the error page (which is what is supposed to happen correct?!?!).  I do have duckDNS set up so when i try to click the webUI link from within the lutron cert add-on window it tries to take me to my https DNS page with port 5817 eg "http://blakeandevon.duckdns.org:5817/" and says site can't be reached of course.  Please help me get my lutron hub integrated.  If i change my internal url (within my config.yaml) back to the IP of my Pi with Home Assistant will this be my correction?  I manually set my internal and external url in the config.yaml because my smartthings webhook wasn't working without adding the urls into my config.
